class STRINGS:
  hello_string = "Здраствуйте\nЧтобы начать работать с заметками зарегестрируйтесь, или войдите в аккаунт"
  add_notes = 'создать заметку'
  add_reminders = 'создать напоминание'
  add_note_text = 'Введите текст заметки'
  add_reminder_text = 'Введите текст напоминания'
  add_reminder_time = 'Введите время в формате hh:mm'
  add_user = "Создать пользователя"
  enter_as_user = "Войти по никнейму"
  register_nick = "Введите свой никнейм"
  create_password = "Придумайте пароль"
  enter_password = "Введите свой пароль"
  no_such_nickname = "Пользователя с таким никнеймом не существует. \n Проверьте введённые данные или зарегестрируйтесь"
  succesfull_enter = "Вход выполнен успешно"
  incorrect_password = "Пароль неверный"
  this_nickname_exists = "Пользователь с таким некнеймом уже существует"
  user_created =  "Пользователь успешно создан"
  note_added = "Заметка созданна"
  show_notes = 'Показать заметки пользователя'
  delete_note = 'Удалить заметку'
  choose_deleted_note = "Введите номер удаляемой заметки"
  number_error = "Это не номер"
  notes_dont_exist = "У вас пока нет заметок"